set -g tide_chruby_bg_color CC342D
set -g tide_chruby_color white
set -g tide_cmd_duration_bg_color C4A000
set -g tide_cmd_duration_color 000000
set -g tide_context_bg_color 444444
set -g tide_git_bg_color 268bd2
set -g tide_git_branch_color 000000
set -g tide_git_conflicted_color 000000
set -g tide_git_dirty_color 000000
set -g tide_git_operation_color 000000
set -g tide_git_staged_color 000000
set -g tide_git_stash_color 000000
set -g tide_git_untracked_color 000000
set -g tide_git_upstream_color 000000
set -g tide_jobs_bg_color 444444
set -g tide_jobs_color 4E9A06
set -g tide_left_prompt_frame_enabled true
set -g tide_left_prompt_item_separator_diff_color \ue0bc
set -g tide_left_prompt_item_separator_same_color \ue0b1
set -g tide_left_prompt_items pwd git newline
set -g tide_left_prompt_pad_items true
set -g tide_left_prompt_prefix \ue0b6
set -g tide_left_prompt_suffix \ue0b0
set -g tide_nvm_bg_color 75507B
set -g tide_nvm_color 2E3436
set -g tide_os_bg_color CED7CF
set -g tide_os_color 080808
set -g tide_php_bg_color 75507B
set -g tide_php_color 000000
set -g tide_print_newline_before_prompt false
set -g tide_pwd_bg_color 444444
set -g tide_pwd_color_anchors E4E4E4
set -g tide_pwd_color_dirs a4a4a4
set -g tide_pwd_color_truncated_dirs BCBCBC
set -g tide_pwd_truncate_margin 100
set -g tide_right_prompt_item_separator_diff_color \ue0ba
set -g tide_right_prompt_item_separator_same_color \ue0b3
set -g tide_right_prompt_items status cmd_duration context jobs nvm virtual_env rust php vi_mode time
set -g tide_right_prompt_pad_items true
set -g tide_right_prompt_prefix \ue0b2
set -g tide_right_prompt_suffix \ue0b4
set -g tide_rust_bg_color FF8700
set -g tide_rust_color 2E3436
set -g tide_status_failure_bg_color CC0000
set -g tide_status_failure_color FFFF00
set -g tide_status_success_bg_color 2E3436
set -g tide_status_success_color 4E9A06
set -g tide_time_bg_color D3D7CF
set -g tide_time_color 000000
set -g tide_vi_mode_default_bg_color 008000
set -g tide_vi_mode_default_color 000000
set -g tide_vi_mode_default_icon DEFAULT
set -g tide_vi_mode_insert_bg_color 444444
set -g tide_vi_mode_replace_bg_color 808000
set -g tide_vi_mode_replace_color 000000
set -g tide_vi_mode_replace_icon REPLACE
set -g tide_vi_mode_visual_bg_color 000080
set -g tide_vi_mode_visual_color 000000
set -g tide_vi_mode_visual_icon VISUAL
set -g tide_virtual_env_bg_color 444444
