[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "buttonless"
opacity = 0.9

[window.padding]
x = 10
y = 10

[colors.primary]
background = '0x0d1117'
foreground = '0xe6edf3'

[colors.cursor]
text = '0x0d1117'
cursor = '0xe6edf3'

[colors.normal]
black = '0x484f58'
red = '0xff7b72'
green = '0x3fb950'
yellow = '0xd29922'
blue = '0x58a6ff'
magenta = '0xbc8cff'
cyan = '0x39c5cf'
white = '0xb1bac4'

[colors.bright]
black = '0x6e7681'
red = '0xffa198'
green = '0x56d364'
yellow = '0xe3b341'
blue = '0x79c0ff'
magenta = '0xbc8cff'
cyan = '0x39c5cf'
white = '0xb1bac4'
