format = """
[╭─](fg:#0077c2)\
$shell\
[](fg:#0077c2 bg:#444444)\
$directory\
[](fg:#444444)\
\n[╰─](fg:#21c7c7)\
$character
"""

right_format = """
[](fg:#40c4ff)\
$time\
[](fg:#40c4ff)
"""

[shell]
style = "fg:#ffffff bg:#0077c2"
format = "[ $indicator ]($style)"
disabled = false

[directory]
style = "fg:#E4E4E4 bg:#444444"
format = "[ $path ]($style)"

[character]
success_symbol = "[❯](fg:#e0f8ff)"

[time]
disabled = false
style = "fg:#ffffff bg:#40c4ff"
format = "[  $time ]($style)"
