"$schema" = 'https://starship.rs/config-scheme.json'

format = """
[╭─](fg:#0077c2)\
$hostname\
[](fg:#0077c2 bg:#444444)\
$directory\
[](fg:#444444 bg:#FFFB38)\
$git_status\
[](fg:#FFFB38)\
\n[╰─](fg:#21c7c7)\
$character
"""

right_format = """
[](fg:#40c4ff)\
$time\
[](fg:#40c4ff)
"""

[hostname]
style = "fg:#ffffff bg:#0077c2"
format = "[ $hostname ]($style)"

[directory]
style = "fg:#E4E4E4 bg:#444444"
format = "[ $path ]($style)"

[git_status]
style = "fg:#011627 bg:#FFFB38"
format = '[ $all_status$ahead_behind ]($style)'

[character]
success_symbol = "[❯](fg:#e0f8ff)"

[time]
disabled = false
style = "fg:#ffffff bg:#40c4ff"
format = "[  $time ]($style)"
